### ISSUE TITLE
js controller 3.3

### ISSUE THREAD

**Issue by Linedancer** [xXBJXx/ioBroker.wallpanel#175]
i am using version 0.1.1
since the update to js controller 3.3 i recieve the following warning:

State value to set for "wallpanel.0.og_flur.lastInfoUpdate" has to be type "boolean" but received type "number"

**Comment by xXBJXx** [comment]
Installiere bitte die neue Version [ v0.1.7-0](https://github.com/xXBJXx/ioBroker.wallpanel/tree/v0.1.7-0) von GitHub
