### ISSUE TITLE
Log Info State value

### ISSUE THREAD

**Issue by Manolo68** [xXBJXx/ioBroker.wallpanel#270]
Habe folgenden Eintrag im Info Log:
"(16658) State value to set for "wallpanel.0.kueche.lastInfoUpdate" has to be type "boolean" but received type "number"
Meldung kommt alle 30 sec, also jeden Abfrageintervall.

**Comment by xXBJXx** [comment]
Installiere dir die neue Version und mache ein Upload
![CleanShot 28-03-2022 at 14 38 29](https://user-images.githubusercontent.com/32600934/160399565-fbba9af4-b022-43bb-8207-0064ecfea14f.png)
 dann lösche den wallpanel.0.kueche.lastInfoUpdate state warte kurz ab dann wird der Adapter ihn neu erstellen

**Comment by Manolo68** [comment]
Perfekt! Danke!
