### ISSUE TITLE
No Connection to the app

### ISSUE THREAD

**Issue by Manolo68** [xXBJXx/ioBroker.wallpanel#297]
Nach Installation des Adapters lässt sich kein Tablet mit der installierten App verbinden.
Die Funktion "Neues Gerät hinzufügen" bleibt in Dauerschleife hängen.
Nach Abbruch ist folgende Meldung im Log:
"[onMessage add] error: AbortController is not defined, stack: ReferenceError: AbortController is not defined at Wallpanel.onMessage (/opt/iobroker/node_modules/iobroker.wallpanel/src/main.ts:1385:6) at Wallpanel.emit (events.js:400:28) at Wallpanel.emit (domain.js:475:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (internal/timers.js:464:21)"

Installiert ist Version 0.3.6 des Adapters und Version 0.10.0.1-release der App.
Der MQTT Broker im ioBroker empfängt aber Daten von der Wallpanel App.

**Comment by xXBJXx** [comment]
Hast du den Adapter neu installiert oder ein Update gemacht?

**Comment by xXBJXx** [comment]
Welche Node Version verwenden sie, der Adapter benötigt eine Node Version ab v15+.
Falls sie eine kleinere Version verwenden, dann bitte auf eine höhere aktualisieren.
Ich habe auf meinem Testsystem die v16 installiert und da funktioniert der Adapter ohne Probleme.

**Comment by Manolo68** [comment]
Der Adapter wurde neu installiert auf einem komplett neu aufgesetzten System.
Node Version ist v14.19.3
Werde auf v16 updaten und dann berichten.
